@IsTest
private class AnimalsCalloutsTest {
    // @isTest static void testGetCallout(){
    //     StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
    //     mock.setStaticResource('GetAnimalResource');
    //     mock.setStatusCode(200);
    //     mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
    //     Test.setMock(HttpCalloutMock.class, mock);
    //     HttpResponse response = AnimalsCallouts.makeGetCallout();
    //     System.assertNotEquals(null, response,'The callout returns a null response.');
    //     System.assertEquals(200, response.getStatusCode(),'Status code is not equal 200');
    //     System.assertEquals('application/json;charset=UTF-8',
    //       response.getHeader('Content-Type'),'The content type value is not expected.');  
        
    //     Map<String, Object> results = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
    //     List<Object> animals = (List<Object>) results.get('animals');
    //     System.assertEquals(3, animals.size(),'The array should only contain 3 items.');   
                
    // }
}