@isTest
public class DropboxCommunityTest {
    // public static testMethod void dropBoxTest(){
    //     Test.setMock(HttpCalloutMock.class, new DropboxCommunityMock());
    //     PageReference pg = Page.DropBox;
    //     Test.setCurrentPage(pg);        
    //     ApexPages.currentPage().getParameters().put('code','4/8wDUjBlcp2cLLcDl9nmCJX_LBPowqao5i8_szg5WoD7JXCSh1TuQgtMYs99ExFQtSojLnFO-1UgxLqZrVrjJVPs');
    //     DropBoxController db = new DropBoxController();
    //     db.getAuthCode();
    //     db.deleteFolder();        
    //     ApexPages.currentPage().getParameters().put('folderName','sHrI');
    //     db.createFolder();
    //     db.viewFile();
    //     ApexPages.currentPage().getParameters().put('folderId','abc');
    //     db.showSubFolder();
    //     db.breadcrumNavigation();
    //     db.recFileName = 'uploadFile';
    //     db.filetype = 'application/oct-stream';
    //     db.fileData = Blob.valueOf('hello,sHri');
    //     db.uploadFile();
    //     ApexPages.currentPage().getParameters().put('fId','home');
    //     db.downloadFile();
    // }
}