public with sharing class GoogleDriveLightningIntegrationWrapper {
	
	private static String key='72641396293-65qjuotve58pr4fnlklg8gvdnj4p4nlj.apps.googleusercontent.com';
    private static String secret = 'rXZ2cMjOtY8_I1iKLh1oDmNU';
    private static String redirectURL='https://brlightcomponent-dev-ed.lightning.force.com/c/LightningComponentShowRecord.app';            
    
	public GoogleDriveLightningIntegrationWrapper() {
		
	}	
     
}