@isTest()
public class GoogleDriveCommunityTest {
    // public static testmethod void communitController(){
    //    Test.setMock(HttpcalloutMock.class, new GoogleDriveCommunityMock());
    //    PageReference pg = Page.GoogleDriveCommunity;
    //    Test.setCurrentPage(pg);
    //    ApexPages.currentPage().getParameters().put('code','4/8wDUjBlcp2cLLcDl9nmCJX_LBPowqao5i8_szg5WoD7JXCSh1TuQgtMYs99ExFQtSojLnFO-1UgxLqZrVrjJVPs');
    //    GoogleDriveControllerForCommunity gd = new GoogleDriveControllerForCommunity();
    //    Apexpages.currentPage().getParameters().put('folderName','FolderName');
    //    ApexPages.currentPage().getParameters().put('folderId','abc');
    //    Community__c cmnty = new Community__c();
    //    cmnty.GoogleDriveRefreshToken__c = 'mittal.shri';
    //    cmnty.userId__c = 'mittal.s@briskminds.com';
    //    insert cmnty;
    //     gd.getAuthCode();
    //    /*gd.getFolderName();
    //     /*gd.deleteFolder();
    //     ApexPages.currentPage().getParameters().put('fileId','abc');
    //     gd.downloadFile();
    //     gd.viewFile();
    //     gd.recFileName = 'abc.txt';
    //     gd.fileType = 'application/oct-stream';
    //     gd.data = Blob.valueOf('e,point_longitude,line,construction,point_granularity');
    //     gd.uploadFile();
    //     gd.showSubFolder();
    //     gd.breadCrumFolderNavigation();*/
    // }
    
    public void authCode(){
      
    }
}