@isTest
public class TestRestrictContactByName {
	// @isTest static void checkLastName(){
    //         List<contact> cont = new List<contact>{new contact(lastName='shri'),
    //             									new contact(lastName='invalidName')
                
    //         };       
    //         insert cont;
        	
    //     	for(contact c : cont){
    //             if(c.lastName!='invalidName'){
    //             	c.lastName = 'invalidName';
    //             }
    //         }
    //     update cont;
    // }
}